### ISSUE TITLE
没有找到fastdfs从文件上传的api

### ISSUE THREAD

**Issue by Yuan0Teng** [coding4m/fastdfs-client#2]
没有找到fastdfs从文件上传的api

**Comment by fanqinghui** [comment]
storageClient.uploadFile(GROUP_NAME, fileInputStream, uploadFileInfo.getFileSize(), uploadFileInfo.getFileExtName());

**Comment by Yuan0Teng** [comment]
不好意思,我表达不清楚,
是 (从文件)  上传   (从文件) 的 id 和主文件(普通上传)的文件id是有关系的
主文件 : id*****.jpg
从文件 : id*****_120_120.jpg
官方的api是有支持的.

**Comment by coding4m** [comment]
未实现该接口。
